MODEL:
  TYPE: swin_polar
  NAME: one_distortion_swin_small_patch2_window4_64_gp2_polar
  DROP_PATH_RATE: 0.2
  P: 4
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
  SWINAZ:
    WINDOW_SIZE: (1,16)
DATA:
  DA: True
  high: 0.2
  low: 0.35